name: retail_suite_mobile
description: Retail Suite Android App (POS + Stock + Transfers + Stock Take + Reports)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.5
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  intl: ^0.19.0
  uuid: ^4.4.2
  pdf: ^3.11.1
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  flutter_contacts: ^1.1.9+2

  mobile_scanner: ^7.2.0
  print_bluetooth_thermal: ^1.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/tone_app_icon.png
    - assets/branding/tone_family_logo.jpg
